[build]
  command = "echo 'Skipping build – using precompiled output.'"
  publish = "build"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "image/x-icon"

[[headers]]
  for = "/logo.svg"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "interest-cohort=()"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:;"
